BEGIN;

CREATE TABLE user_roles (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE source_types (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE job_statuses (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE severity_levels (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    rank SMALLINT NOT NULL UNIQUE,

    CONSTRAINT chk_severity_levels_rank
        CHECK (rank BETWEEN 0 AND 4)
);

CREATE TABLE event_outcomes (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_role_code VARCHAR(20) NOT NULL DEFAULT 'user',
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_role
        FOREIGN KEY (fk_role_code)
        REFERENCES user_roles(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_users_username_not_empty
        CHECK (length(trim(username)) > 0),

    CONSTRAINT chk_users_email_not_empty
        CHECK (length(trim(email)) > 0),

    CONSTRAINT chk_users_password_hash_not_empty
        CHECK (length(trim(password_hash)) > 0)
);

CREATE UNIQUE INDEX uq_users_username_ci
    ON users (lower(username));

CREATE UNIQUE INDEX uq_users_email_ci
    ON users (lower(email));

CREATE INDEX idx_users_role
    ON users(fk_role_code);

CREATE TABLE uploads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_user_id BIGINT NOT NULL,
    fk_source_type_code VARCHAR(30) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    file_path TEXT NOT NULL,
    mime_type VARCHAR(100),
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_uploads_user
        FOREIGN KEY (fk_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_uploads_source_type
        FOREIGN KEY (fk_source_type_code)
        REFERENCES source_types(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_uploads_stored_filename
        UNIQUE (stored_filename),

    CONSTRAINT uq_uploads_file_path
        UNIQUE (file_path),

    CONSTRAINT chk_uploads_original_filename_not_empty
        CHECK (length(trim(original_filename)) > 0),

    CONSTRAINT chk_uploads_stored_filename_not_empty
        CHECK (length(trim(stored_filename)) > 0),

    CONSTRAINT chk_uploads_file_path_not_empty
        CHECK (length(trim(file_path)) > 0),

    CONSTRAINT chk_uploads_size
        CHECK (size_bytes > 0),

    CONSTRAINT chk_uploads_sha256
        CHECK (sha256 ~ '^[0-9a-fA-F]{64}$')
);

CREATE INDEX idx_uploads_user
    ON uploads(fk_user_id);

CREATE INDEX idx_uploads_source_type
    ON uploads(fk_source_type_code);

CREATE TABLE analysis_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_upload_id BIGINT NOT NULL,
    fk_status_code VARCHAR(20) NOT NULL DEFAULT 'queued',
    progress SMALLINT NOT NULL DEFAULT 0,
    processed_records BIGINT NOT NULL DEFAULT 0,
    events_created BIGINT NOT NULL DEFAULT 0,
    findings_created INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_analysis_jobs_upload
        FOREIGN KEY (fk_upload_id)
        REFERENCES uploads(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_analysis_jobs_status
        FOREIGN KEY (fk_status_code)
        REFERENCES job_statuses(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_analysis_jobs_progress
        CHECK (progress BETWEEN 0 AND 100),

    CONSTRAINT chk_analysis_jobs_processed_records
        CHECK (processed_records >= 0),

    CONSTRAINT chk_analysis_jobs_events_created
        CHECK (events_created >= 0),

    CONSTRAINT chk_analysis_jobs_findings_created
        CHECK (findings_created >= 0),

    CONSTRAINT chk_analysis_jobs_time_order
        CHECK (
            finished_at IS NULL
            OR started_at IS NULL
            OR finished_at >= started_at
        )
);

CREATE INDEX idx_analysis_jobs_upload
    ON analysis_jobs(fk_upload_id);

CREATE INDEX idx_analysis_jobs_status
    ON analysis_jobs(fk_status_code);


CREATE TABLE event_types (
    code VARCHAR(50) PRIMARY KEY,
    fk_source_type_code VARCHAR(30),
    name VARCHAR(150) NOT NULL,
    description TEXT,

    CONSTRAINT fk_event_types_source_type
        FOREIGN KEY (fk_source_type_code)
        REFERENCES source_types(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_event_types_source_type
    ON event_types(fk_source_type_code);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_job_id BIGINT NOT NULL,
    fk_event_type_code VARCHAR(50) NOT NULL,
    fk_severity_code VARCHAR(20) NOT NULL DEFAULT 'info',
    fk_outcome_code VARCHAR(20),
    occurred_at TIMESTAMPTZ NOT NULL,
    source_ip INET,
    destination_ip INET,
    source_port INTEGER,
    destination_port INTEGER,
    protocol VARCHAR(20),
    hostname VARCHAR(255),
    username VARCHAR(100),
    process_name VARCHAR(100),
    message TEXT,
    raw_event TEXT NOT NULL,
    source_line_number BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_events_job
        FOREIGN KEY (fk_job_id)
        REFERENCES analysis_jobs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_events_event_type
        FOREIGN KEY (fk_event_type_code)
        REFERENCES event_types(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_events_severity
        FOREIGN KEY (fk_severity_code)
        REFERENCES severity_levels(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_events_outcome
        FOREIGN KEY (fk_outcome_code)
        REFERENCES event_outcomes(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_events_source_port
        CHECK (source_port IS NULL OR source_port BETWEEN 0 AND 65535),

    CONSTRAINT chk_events_destination_port
        CHECK (destination_port IS NULL OR destination_port BETWEEN 0 AND 65535),

    CONSTRAINT chk_events_source_line_number
        CHECK (source_line_number IS NULL OR source_line_number > 0),

    CONSTRAINT chk_events_raw_event_not_empty
        CHECK (length(raw_event) > 0)
);

CREATE INDEX idx_events_event_type
    ON events(fk_event_type_code);

CREATE INDEX idx_events_severity
    ON events(fk_severity_code);

CREATE INDEX idx_events_outcome
    ON events(fk_outcome_code);

CREATE INDEX idx_events_job_occurred_at
    ON events(fk_job_id, occurred_at DESC);


CREATE TABLE http_event_details (
    fk_event_id BIGINT PRIMARY KEY,
    http_method VARCHAR(10),
    request_path TEXT,
    status_code SMALLINT,
    response_size BIGINT,
    http_version VARCHAR(20),
    user_agent TEXT,
    referer TEXT,

    CONSTRAINT fk_http_event_details_event
        FOREIGN KEY (fk_event_id)
        REFERENCES events(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_http_event_details_status_code
        CHECK (status_code IS NULL OR status_code BETWEEN 100 AND 599),

    CONSTRAINT chk_http_event_details_response_size
        CHECK (response_size IS NULL OR response_size >= 0)
);

CREATE TABLE suricata_event_details (
    fk_event_id BIGINT PRIMARY KEY,
    suricata_event_type VARCHAR(30) NOT NULL,
    flow_id NUMERIC(20, 0),
    signature_id BIGINT,
    signature TEXT,
    category VARCHAR(255),
    suricata_severity SMALLINT,

    CONSTRAINT fk_suricata_event_details_event
        FOREIGN KEY (fk_event_id)
        REFERENCES events(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_suricata_event_details_type_not_empty
        CHECK (length(trim(suricata_event_type)) > 0),

    CONSTRAINT chk_suricata_event_details_flow_id
        CHECK (flow_id IS NULL OR flow_id >= 0),

    CONSTRAINT chk_suricata_event_details_signature_id
        CHECK (signature_id IS NULL OR signature_id >= 0),

    CONSTRAINT chk_suricata_event_details_severity
        CHECK (suricata_severity IS NULL OR suricata_severity >= 0)
);

CREATE TABLE network_event_details (
    fk_event_id BIGINT PRIMARY KEY,
    source_mac MACADDR,
    destination_mac MACADDR,
    packet_size INTEGER,
    tcp_syn BOOLEAN NOT NULL DEFAULT FALSE,
    tcp_ack BOOLEAN NOT NULL DEFAULT FALSE,
    tcp_fin BOOLEAN NOT NULL DEFAULT FALSE,
    tcp_rst BOOLEAN NOT NULL DEFAULT FALSE,
    tcp_psh BOOLEAN NOT NULL DEFAULT FALSE,
    tcp_urg BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_network_event_details_event
        FOREIGN KEY (fk_event_id)
        REFERENCES events(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_network_event_details_packet_size
        CHECK (packet_size IS NULL OR packet_size >= 0)
);

CREATE TABLE dns_event_details (
    fk_event_id BIGINT PRIMARY KEY,
    query_name VARCHAR(253),
    query_type VARCHAR(20),
    response_code VARCHAR(20),

    CONSTRAINT fk_dns_event_details_event
        FOREIGN KEY (fk_event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);

CREATE TABLE dns_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_event_id BIGINT NOT NULL,
    answer_type VARCHAR(20) NOT NULL,
    answer_value TEXT NOT NULL,
    ttl_seconds INTEGER,

    CONSTRAINT fk_dns_answers_event
        FOREIGN KEY (fk_event_id)
        REFERENCES dns_event_details(fk_event_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_dns_answers_type_not_empty
        CHECK (length(trim(answer_type)) > 0),

    CONSTRAINT chk_dns_answers_value_not_empty
        CHECK (length(trim(answer_value)) > 0),

    CONSTRAINT chk_dns_answers_ttl
        CHECK (ttl_seconds IS NULL OR ttl_seconds >= 0)
);

CREATE INDEX idx_dns_answers_event
    ON dns_answers(fk_event_id);


CREATE TABLE detection_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_source_type_code VARCHAR(30),
    fk_severity_code VARCHAR(20) NOT NULL,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(150) NOT NULL,
    description TEXT NOT NULL,
    threshold_value INTEGER,
    time_window_seconds INTEGER,
    recommendation TEXT,
    is_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_detection_rules_source_type
        FOREIGN KEY (fk_source_type_code)
        REFERENCES source_types(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_detection_rules_severity
        FOREIGN KEY (fk_severity_code)
        REFERENCES severity_levels(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_detection_rules_code
        UNIQUE (code),

    CONSTRAINT chk_detection_rules_code_not_empty
        CHECK (length(trim(code)) > 0),

    CONSTRAINT chk_detection_rules_name_not_empty
        CHECK (length(trim(name)) > 0),

    CONSTRAINT chk_detection_rules_threshold
        CHECK (threshold_value IS NULL OR threshold_value > 0),

    CONSTRAINT chk_detection_rules_time_window
        CHECK (time_window_seconds IS NULL OR time_window_seconds > 0)
);

CREATE INDEX idx_detection_rules_source_type
    ON detection_rules(fk_source_type_code);

CREATE INDEX idx_detection_rules_severity
    ON detection_rules(fk_severity_code);

CREATE TABLE rule_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_rule_id BIGINT NOT NULL,
    field_name VARCHAR(100) NOT NULL,
    comparison_operator VARCHAR(20) NOT NULL,
    comparison_value TEXT NOT NULL,

    CONSTRAINT fk_rule_conditions_rule
        FOREIGN KEY (fk_rule_id)
        REFERENCES detection_rules(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_rule_conditions_field_name_not_empty
        CHECK (length(trim(field_name)) > 0),

    CONSTRAINT chk_rule_conditions_operator
        CHECK (
            comparison_operator IN (
                'equals',
                'not_equals',
                'contains',
                'starts_with',
                'ends_with',
                'regex',
                'greater_than',
                'less_than'
            )
        ),

    CONSTRAINT chk_rule_conditions_value_not_empty
        CHECK (length(trim(comparison_value)) > 0)
);

CREATE INDEX idx_rule_conditions_rule
    ON rule_conditions(fk_rule_id);

CREATE TABLE findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_job_id BIGINT NOT NULL,
    fk_rule_id BIGINT NOT NULL,
    fk_severity_code VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    source_ip INET,
    destination_ip INET,
    username VARCHAR(100),
    first_seen TIMESTAMPTZ NOT NULL,
    last_seen TIMESTAMPTZ NOT NULL,
    recommendation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_findings_job
        FOREIGN KEY (fk_job_id)
        REFERENCES analysis_jobs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_findings_rule
        FOREIGN KEY (fk_rule_id)
        REFERENCES detection_rules(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_findings_severity
        FOREIGN KEY (fk_severity_code)
        REFERENCES severity_levels(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_findings_title_not_empty
        CHECK (length(trim(title)) > 0),

    CONSTRAINT chk_findings_time_order
        CHECK (last_seen >= first_seen)
);

CREATE INDEX idx_findings_job
    ON findings(fk_job_id);

CREATE INDEX idx_findings_rule
    ON findings(fk_rule_id);

CREATE INDEX idx_findings_severity
    ON findings(fk_severity_code);

CREATE TABLE finding_events (
    fk_finding_id BIGINT NOT NULL,
    fk_event_id BIGINT NOT NULL,

    CONSTRAINT pk_finding_events
        PRIMARY KEY (fk_finding_id, fk_event_id),

    CONSTRAINT fk_finding_events_finding
        FOREIGN KEY (fk_finding_id)
        REFERENCES findings(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_finding_events_event
        FOREIGN KEY (fk_event_id)
        REFERENCES events(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_finding_events_event
    ON finding_events(fk_event_id);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_job_id BIGINT NOT NULL,
    fk_risk_level_code VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reports_job
        FOREIGN KEY (fk_job_id)
        REFERENCES analysis_jobs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_reports_risk_level
        FOREIGN KEY (fk_risk_level_code)
        REFERENCES severity_levels(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_reports_job
        UNIQUE (fk_job_id),

    CONSTRAINT chk_reports_title_not_empty
        CHECK (length(trim(title)) > 0),

    CONSTRAINT chk_reports_summary_not_empty
        CHECK (length(trim(summary)) > 0)
);

CREATE INDEX idx_reports_risk_level
    ON reports(fk_risk_level_code);


CREATE TABLE job_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fk_job_id BIGINT NOT NULL,
    fk_old_status_code VARCHAR(20),
    fk_new_status_code VARCHAR(20) NOT NULL,
    message TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_job_status_history_job
        FOREIGN KEY (fk_job_id)
        REFERENCES analysis_jobs(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_job_status_history_old_status
        FOREIGN KEY (fk_old_status_code)
        REFERENCES job_statuses(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_job_status_history_new_status
        FOREIGN KEY (fk_new_status_code)
        REFERENCES job_statuses(code)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_job_status_history_status_changed
        CHECK (
            fk_old_status_code IS NULL
            OR fk_old_status_code <> fk_new_status_code
        )
);

CREATE INDEX idx_job_status_history_job
    ON job_status_history(fk_job_id);

CREATE INDEX idx_job_status_history_old_status
    ON job_status_history(fk_old_status_code);

CREATE INDEX idx_job_status_history_new_status
    ON job_status_history(fk_new_status_code);


INSERT INTO user_roles (code, name)
VALUES
    ('user', 'Пользователь'),
    ('admin', 'Администратор');

INSERT INTO source_types (code, name, description)
VALUES
    ('auth_log', 'Linux auth.log', 'Журнал аутентификации Linux, SSH и sudo'),
    ('nginx_access', 'Nginx access.log', 'Журнал HTTP-запросов Nginx'),
    ('suricata_eve', 'Suricata eve.json', 'Журнал IDS-событий Suricata'),
    ('pcap', 'PCAP/PCAPNG', 'Дамп сетевого трафика');

INSERT INTO job_statuses (code, name)
VALUES
    ('queued', 'Ожидает обработки'),
    ('processing', 'Обрабатывается'),
    ('completed', 'Завершена'),
    ('failed', 'Ошибка'),
    ('cancelled', 'Отменена');

INSERT INTO severity_levels (code, name, rank)
VALUES
    ('info', 'Информационный', 0),
    ('low', 'Низкий', 1),
    ('medium', 'Средний', 2),
    ('high', 'Высокий', 3),
    ('critical', 'Критический', 4);

INSERT INTO event_outcomes (code, name)
VALUES
    ('success', 'Успешно'),
    ('failure', 'Неуспешно'),
    ('unknown', 'Неизвестно');

INSERT INTO event_types (code, fk_source_type_code, name, description)
VALUES
    ('failed_ssh_login', 'auth_log', 'Неудачный вход по SSH', 'Неудачная попытка SSH-аутентификации'),
    ('successful_ssh_login', 'auth_log', 'Успешный вход по SSH', 'Успешная SSH-аутентификация'),
    ('invalid_user_login', 'auth_log', 'Вход неизвестного пользователя', 'Попытка входа с неизвестным именем пользователя'),
    ('sudo_command', 'auth_log', 'Выполнение sudo', 'Запуск команды с использованием sudo'),
    ('web_request', 'nginx_access', 'HTTP-запрос', 'Запрос из журнала Nginx'),
    ('ids_alert', 'suricata_eve', 'IDS-событие', 'Срабатывание сигнатуры Suricata'),
    ('dns_query', NULL, 'DNS-запрос', 'Запрос доменного имени'),
    ('network_packet', 'pcap', 'Сетевой пакет', 'Пакет из PCAP или PCAPNG');

INSERT INTO detection_rules (
    fk_source_type_code,
    fk_severity_code,
    code,
    name,
    description,
    threshold_value,
    time_window_seconds,
    recommendation
)
VALUES
    (
        'auth_log',
        'high',
        'SSH_BRUTE_FORCE',
        'Possible SSH Brute Force',
        'Много неудачных попыток входа по SSH с одного IP-адреса',
        10,
        120,
        'Проверить источник соединений и при подтверждении атаки ограничить доступ с IP-адреса.'
    ),
    (
        'auth_log',
        'high',
        'SUCCESS_AFTER_FAILURES',
        'Successful Login After Failures',
        'Успешный вход после серии неудачных попыток аутентификации',
        5,
        300,
        'Проверить успешную сессию и убедиться, что учетная запись не была скомпрометирована.'
    ),
    (
        'nginx_access',
        'medium',
        'SENSITIVE_PATH_PROBING',
        'Sensitive Path Probing',
        'Запросы к потенциально конфиденциальным путям веб-приложения',
        1,
        NULL,
        'Проверить IP-адрес и убедиться, что конфиденциальные файлы недоступны извне.'
    ),
    (
        'nginx_access',
        'medium',
        'WEB_SCANNING',
        'Possible Web Scanning',
        'Обращение одного источника к большому количеству различных URL',
        20,
        60,
        'Проверить запросы источника и при необходимости настроить ограничение частоты запросов.'
    ),
    (
        'nginx_access',
        'medium',
        'HIGH_HTTP_ERROR_RATE',
        'High HTTP Error Rate',
        'Большое количество HTTP-ответов с кодами ошибок для одного источника',
        30,
        60,
        'Проверить ошибки сервера и активность IP-адреса.'
    ),
    (
        'pcap',
        'high',
        'PORT_SCAN',
        'Possible Port Scan',
        'Один источник обращается к большому количеству портов назначения',
        20,
        30,
        'Проверить источник трафика и ограничить сетевой доступ при подтверждении сканирования.'
    ),
    (
        'suricata_eve',
        'critical',
        'CRITICAL_SURICATA_ALERT',
        'Critical Suricata Alert',
        'Suricata зарегистрировала событие высокой критичности',
        1,
        NULL,
        'Изучить сигнатуру, связанные сетевые соединения и затронутые узлы.'
    );

COMMIT;
